# GENERATED BY MCDC LLM AGENT

import mcdc
import numpy as np

m2 = mcdc.MaterialMG(
    capture=np.array([1.5])
)
m1 = mcdc.MaterialMG(
    capture=np.array([1.0])
)
m3 = mcdc.MaterialMG(
    capture=np.array([2.0])
)
s1 = mcdc.Surface.PlaneZ(z=0.0, boundary_condition='vacuum')
s3 = mcdc.Surface.PlaneZ(z=4.0)
s2 = mcdc.Surface.PlaneZ(z=2.0)
s4 = mcdc.Surface.PlaneZ(z=6.0, boundary_condition='vacuum')
# Cell between s1 and s2, filled with m2
cell1 = mcdc.Cell(region=+s1 & -s2, fill=m2)
# Cell between s2 and s3, filled with m3
cell2 = mcdc.Cell(region=+s2 & -s3, fill=m3)
# Cell between s3 and s4, filled with m1
cell3 = mcdc.Cell(region=+s3 & -s4, fill=m1)
source = mcdc.Source(z=np.array([0.0, 6.0]), isotropic=True, energy_group=0)
tally_s4 = mcdc.TallySurface(scores=['net-current'], surface=s4)
# Structured mesh for z-axis
mesh_z = mcdc.MeshStructured(z=np.linspace(0, 6, 60))
tally_mesh_z = mcdc.TallyMesh(scores=['flux', 'collision'], mesh=mesh_z, mu=np.linspace(-1, 1, 32))
mcdc.settings.N_particle = 100
mcdc.settings.N_batch = 2

mcdc.run()
